### ISSUE TITLE
New design.

### ISSUE THREAD

**Issue by itsjohncs** [itsjohncs/blog.johncs.com#14]
I think I can improve the design by making it two columns. A list of posts on the left, and the content on the right.

**Comment by brownhead** [comment]
I did this on the [KA Engineering](http://engineering.khanacademy.org) blog and I think it looks/works great. I have some crazy ideas around a totally monospace design, but I think it might be too distracting.

**Comment by brownhead** [comment]
Hmm... I spent a lot of time working on the KA Engineering blog, and I did it fairly recently. I'm afraid of doing nearly the same thing, which I don't really want to do...

My long-term goal is to swallow my portfolio into this site as well so like the KA site, there's a lot of components to the site, certainly more than what the current layout can handle.

**Comment by brownhead** [comment]
Well I guess the content doesn't necessarily look too bad...

![screen shot 2015-06-09 at 10 54 05 pm](https://cloud.githubusercontent.com/assets/367832/8075881/87440b7a-0efa-11e5-8baf-e679229d135b.png)

That's with an expensive web font though...

**Comment by brownhead** [comment]
I'm pretty torn between doing something unique like this then working hard to make it usable, versus doing something more typical and working to make it seem unique. Both seem like difficult tasks.

The reliance on **three font weights** of a web font for the monospace thing to work makes me pretty worried...

**Comment by brownhead** [comment]
Codepen: http://codepen.io/anon/pen/vOZEJo?editors=110

I think I'm pretty much off the idea at this point. I don't think a monospace layout will end up working out well. At least an all monospace one. I'll think on what layout would make sense some more though, and how I can make it a little unique.

**Comment by brownhead** [comment]
Oh! Jordan has a monospace layout: http://thatjdanisso.cool/. Interesting... It feels very useable too.

**Comment by brownhead** [comment]
![screen shot 2015-06-12 at 12 20 56 am](https://cloud.githubusercontent.com/assets/367832/8125243/f6dcf3da-1098-11e5-918f-f4a66e981123.png)

Oh god yes.

**Comment by brownhead** [comment]
![screen shot 2015-06-12 at 12 42 01 am](https://cloud.githubusercontent.com/assets/367832/8125603/e8058cc0-109b-11e5-9d56-b252cdd61cef.png)

I'm digging this pretty hard.

**Comment by brownhead** [comment]
Was having a lot of trouble trying to tell the user where the hell they were, so I think for post pages, a different chrome should be shown maybe...

![screen shot 2015-06-12 at 1 25 50 am](https://cloud.githubusercontent.com/assets/367832/8126293/104eb480-10a2-11e5-9ca0-ee434f4b20ac.png)

**Comment by brownhead** [comment]
http://imgur.com/a/PBq91

**Comment by brownhead** [comment]
It might be wise to make this look a little more retro by default. I like the solarized color scheme but it does seem kinda out of place with the ASCII banner. I could look at mIRC's default color scheme maybe and try to follow suit and see how that works out.

**Comment by brownhead** [comment]
Alternatively, getting rid of the ASCII art banner or at least making other things look a little more updated could be another way to go. This'd probably be better from an aesthetic standpoint, but going retro could get my more overall style points.

**Comment by brownhead** [comment]
Ideas from Lauren and Tom:

* Number the posts on the blog index (keyboard navigation!). This'll let me stick the date after the title too.
* Contrast the titles more on the blog index. They are a little too quiet.
